[project]
name = "pizza-delivery"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Shrey", email = "331877214+shreykr77@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.65.0",
]

[project.scripts]
pizza-delivery = "pizza_delivery.main:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
