[project]
name = "pizza-delivery"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Shrey", email = "331877214+shreykr77@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "rosa-starter",
    "streamlit>=1.65.0",
]

[project.scripts]
pizza-delivery = "pizza_delivery.main:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
rosa-starter = { git = "https://github.com/zhouy185/rosa-starter.git", rev = "09f3f0b98fd2fee1ba08322bf8db12c4940590bd" }
