"""Assignment1_PizzaDelivery.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1czSOgRJfbrdW-l3ZdaaXMXT8U_oSEIzp

"""

import numpy as np
from starter import ZONES, TIME_BLOCKS, COSTS, PROMISE, delivery_times

refund = COSTS["refund"]
churn_orders = COSTS["churn_orders"]
margin = COSTS["margin"]
promise_time = 45

def best_promise(query_zones, query_time_blocks, promises, costs):
    all_results = []
    best_results = []

    for query_zone in query_zones:
        for query_time_block in query_time_blocks:

            results = []

            for promise_time in promises:
                deliv_times = delivery_times(
                    query_zone,
                    query_time_block,
                    promise_time
                )

                total_orders = len(deliv_times)
                late_orders = sum(
                    t > promise_time for t in deliv_times
                )
                on_time_orders = total_orders - late_orders

                profit = costs["margin"] * total_orders

                late_cost = late_orders * (
                    costs["refund"] + costs["churn_orders"] * costs["margin"]
                )

                net_profit = profit - late_cost

                results.append({
                    "zone": query_zone,
                    "time_block": query_time_block,
                    "promise_time": promise_time,
                    "on_time_orders": on_time_orders,
                    "late_orders": late_orders,
                    "total_orders": total_orders,
                    "profit": profit,
                    "late_cost": late_cost,
                    "net_profit": net_profit
                })

            # Sort promises within this zone-time block
            results = sorted(
                results,
                key=lambda x: x["net_profit"],
                reverse=True
            )

            # Best promise for this specific
            # zone + time-block combination
            best_results.append(results[0])

            # Store every tested promise
            all_results.extend(results)


    return all_results, best_results

def main():
    query_zones = [
        "Far West",
        "Central"
    ]

    query_time_blocks = [
        "Fri/Sat eve",
        "Lunch"
    ]

    query_promises = range(5, 91, 5)

    all_results, best_results = best_promise(
        query_zones,
        query_time_blocks,
        query_promises,
        COSTS
    )

    for zone in query_zones:

        for time_block in query_time_blocks:

            combination_results = [
                result
                for result in all_results
                if result["zone"] == zone
                and result["time_block"] == time_block
            ]

            print()
            print("=" * 105)
            print(f"{zone} — {time_block}")
            print("=" * 105)

            print(
                f"{'Rank':<6}"
                f"{'Promise':>12}"
                f"{'On Time':>12}"
                f"{'Late':>10}"
                f"{'Orders':>10}"
                f"{'Profit':>14}"
                f"{'Late Cost':>14}"
                f"{'Net Profit':>15}"
            )

            print("-" * 105)

            for rank, result in enumerate(combination_results, 1):

                print(
                    f"{rank:<6}"
                    f"{result['promise_time']:>8} min"
                    f"{result['on_time_orders']:>12}"
                    f"{result['late_orders']:>10}"
                    f"{result['total_orders']:>10}"
                    f"${result['profit']:>13.2f}"
                    f"${result['late_cost']:>13.2f}"
                    f"${result['net_profit']:>14.2f}"
                )

    print()
    print("=" * 105)
    print("BEST PROMISE BY ZONE + TIME BLOCK")
    print("=" * 105)

    print(
        f"{'Zone':<15}"
        f"{'Time Block':<20}"
        f"{'Promise':>12}"
        f"{'On Time':>12}"
        f"{'Late':>10}"
        f"{'Orders':>10}"
        f"{'Net Profit':>15}"
    )

    print("-" * 105)

    for best in best_results:

        print(
            f"{best['zone']:<15}"
            f"{best['time_block']:<20}"
            f"{best['promise_time']:>8} min"
            f"{best['on_time_orders']:>12}"
            f"{best['late_orders']:>10}"
            f"{best['total_orders']:>10}"
            f"${best['net_profit']:>14.2f}"
        )

    print("=" * 105)